
language: node_js
node_js:
  - "8"
  - "6.11.5"
before_script:
  - yarn bootstrap
script:
  - npm test
  - yarn build
  - cd packages/cra-universal/templates
  - yarn crau:build
after_script:
  - yarn global add codecov
  - codecov