
language: node_js
node_js:
  - "12.16.1"
  - "11"
  - "10"
before_script:
  - yarn bootstrap
script:
  - npm test
  - yarn build
  - yarn crau:build
after_script:
  - yarn global add codecov
  - codecov